### ISSUE TITLE
Documentation or example needed

### ISSUE THREAD

**Issue by jbosnjakovic** [clshortfuse/react-native-pcm-audio#1]
Can someone provide an example how to use this library?

**Comment by clshortfuse** [comment]
Done and done. :)

**Comment by jbosnjakovic** [comment]
Wow, that was quick. Thank you so much, I will give it a try. 👍

**Comment by jbosnjakovic** [comment]
@clshortfuse I tried to implement this library in my use case but without luck. I am new in this technology and don't know if this what I want is even possible with this library. I would appreciate any of your help.

My use case: 
- Record PCM 
- Take recording buffer and send it to the speech-to-text service
- Play response back to the user
